spring:
  application:
    name: AI_SQL_Assistant-GenAI-Project

  datasource:
    url: jdbc:postgresql://localhost:5432/AiSQLAssistant
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update


jwt:
  private:
    key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHz09pqK04+UPgwP9LeUGlBodYapeEVGxPRDyfW9SypaOl3xOPbfGgh4c4JxDXcdj+wibkUWPSkZU50i/wTcRUXw3WLIz8mMQETFpHFJRhnLyH/c9kXBzljFtuwidNP6Yn0CjNU9R8+GRcqAGRr0U2f/QDHGi7FWrweuBaaUPsQigDKXtDqhCAg23b4eJamnauk4DFJ0nrxmeZX0eFQjskc80WEWFomySiW0K+j/NVm8tFyQ2m69lU3ze0tQe5OZ6dndVk3nRbo+QLZ7dDHu69KMGYqlShJ1tcHCoaxHLrlGigBhlnA6L9uri1weBC+Cm9JSCu5GZWR5tWtrcKaOhRAgMBAAECggEAXQsmmbcYYu2ANErrFwQyE1zE7eFFCTQe85J9AGBM3ZvQZs9IVoQF/pDd4MIgT5MOTyOt5KgZ6dYtPS2pcSdlgzx4PwGj7YRd0vqTF4J3zjSkflcsmjlio2oGsb7rekdnYibGuUaOLluksJjzkhmiC0zuHfy+sE+66pztmGxoWr1pA3GcUvFGJHHDfSXPtIAszm1tl9ryefcTOUlC8+hznTKIVQXB20JgDb+sc9YsWBmsNopAEgUVm7EszjN8cWg+vw2oHs/Wfq7mUYJJqgGfWUxP714RSdfIze+PT6fLihaDY88djGDn6aITmJLvipC+sLPD4fL4eqr1PWUVTmpO+QKBgQDrRWtdYwB6tCRp6WP14WjIbr2keRbrCN4HpzpCOIsV73pno6V6b7vHuzuediefNIQOfnH1GOLnq6sP70d/pwlFGY3e4ixbYOgpFl+W+qTeOArfa38nGB3vQZnfwB4wNJ09Q9cQI5y16+TVGyJdoNF3qARlFCnYyVrmSInyZheGgwKBgQDZag3GmV0W+8RVCh6oJ6ivhPRgsLioZTwuwLLihyeWtMewpSeDCjfM1nuttzKOj6tweaRh4n9TVH17vsgfMM0UN03kykRDtL6stccFhXeWQiVWwyvxsUrlvTE6+edyKTdhGBTreLt2fETO5U9Mbl/+yqJdGiBAXNRqOiC7r+n9mwKBgQDT9kL4a81uvwVfdincyCvDCCJLH90J+38tnffa2V5VcN/yp3jaife/xmu8I+8mfAXNmRXKH5Wt6ve+73CXDUJIwvESMOqNmQ0Ql1ufhkkq+4qwJwTzj8LIX23mLAwGmiBfpdMIc00oiVIsvLmFaPHOv8zV1AivixkeB5RgkqH3SQKBgFyIc8aD/YfLrfsXrIabIoNZjf0dGeqp85xebYRWS7YryRXYpOFz1t36p3b/Eqh0Y14il6EFmnVn72RchaYoyhABnchzgexjIAg38bXa4VP1YRj1Rl2+vIbdJ/fW5vfCrQxJCJZTs02xhEOee0qna3nw2nvPo8xg9hMkHExliaxjAoGAWFyLVG/WHBhJ83WuAJVbdXAZkk0lTOhKYZNqOFjTw+JmVqXQ2oVct6ShsxSqjQ6uk60IzTWd/jDJbsYZm9kgz/DMDdmNdAKhdSlkm1VV8NNlYxVgcb/bfGio/JW6bqAwQonfY3ITVgVq1JZxNsDkMI++YHZezMCZUgD/FT5StVg=

  public:
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx89PaaitOPlD4MD/S3lBpQaHWGqXhFRsT0Q8n1vUsqWjpd8Tj23xoIeHOCcQ13HY/sIm5FFj0pGVOdIv8E3EVF8N1iyM/JjEBExaRxSUYZy8h/3PZFwc5YxbbsInTT+mJ9AozVPUfPhkXKgBka9FNn/0AxxouxVq8HrgWmlD7EIoAyl7Q6oQgINt2+HiWpp2rpOAxSdJ68ZnmV9HhUI7JHPNFhFhaJskoltCvo/zVZvLRckNpuvZVN83tLUHuTmenZ3VZN50W6PkC2e3Qx7uvSjBmKpUoSdbXBwqGsRy65RooAYZZwOi/bq4tcHgQvgpvSUgruRmVkebVra3CmjoUQIDAQAB


logging:
  level:
    org:
      springframework:
      security: DEBUG
      
      
gemini:
  api:
    key: AIzaSyAv5w_rgsfx04rlVyOXo2MxkK9fC9Upe6Q
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

